<?php

/**
 * Popular SMS Bower service codes (fallback when getServicesList is unavailable).
 * @see https://documenter.getpostman.com/view/16514200/2sAYdkFTue
 */
return [
    'tg' => 'Telegram',
    'wa' => 'WhatsApp',
    'go' => 'Google',
    'fb' => 'Facebook',
    'ig' => 'Instagram',
    'tw' => 'Twitter',
    'ds' => 'Discord',
    'nf' => 'Netflix',
    'am' => 'Amazon',
    'ub' => 'Uber',
    'oi' => 'Tinder',
    'lf' => 'TikTok',
    'mm' => 'Microsoft',
    'hw' => 'Alipay',
    'uk' => 'Airbnb',
    'pd' => 'iFood',
    'sn' => 'OLX',
    'wx' => 'Apple',
    'vi' => 'Viber',
    'me' => 'Line',
    'ya' => 'Yandex',
    'vk' => 'VKontakte',
    'ok' => 'Odnoklassniki',
    'ma' => 'Mail.ru',
    'mb' => 'Yahoo',
    'pf' => 'pof.com',
    'pm' => 'AOL',
    'tn' => 'LinkedIn',
    'dh' => 'eBay',
    'ew' => 'Nike',
    'bz' => 'Blizzard',
    'ep' => 'Temu',
    'dl' => 'Lazada',
    'ka' => 'Shopee',
    'cq' => 'Mercado',
    'nv' => 'Naver',
    'kt' => 'KakaoTalk',
    'li' => 'Baidu',
    'wb' => 'WeChat',
    'qq' => 'Tencent QQ',
    'bd' => 'X5ID',
    'fu' => 'Snapchat',
    'zk' => 'Deliveroo',
    'ac' => 'DoorDash',
    'do' => 'Leboncoin',
    'fr' => 'Dana',
    'sg' => 'OZON',
    'uu' => 'Wildberries',
    'ab' => 'Alibaba',
    'gp' => 'Ticketmaster',
    'tc' => 'Rambler',
    'df' => 'Happn',
    'mo' => 'Bumble',
    'za' => 'JDcom',
    'cn' => 'Fiverr',
    'vr' => 'MotorkuX',
    'ev' => 'Picpay',
    'ue' => 'Onet',
    'im' => 'Imo',
    'yl' => 'Yalla',
    'gj' => 'Carousell',
    'kc' => 'Vinted',
    'pc' => 'Casino/bet',
    'ft' => 'Bookmakers',
    'ot' => 'Other',
];
